### ISSUE TITLE
Trying to run_training_pipeline.py, got RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by Hardog4** [DigitalPhonetics/IMS-Toucan#104]
After creating my own pipeline as described in README, I've got 
python run_training_pipeline.py fine_ex
...
Traceback (most recent call last):
  File "/home/joe/tmp/IMS-Toucan/run_training_pipeline.py", line 71, in <module>
    pipeline_dict[args.pipeline](gpu_id=args.gpu_id,
  File "/home/joe/tmp/IMS-Toucan/TrainingInterfaces/TrainingPipelines/finetuning_example.py", line 52, in run
    russian_datasets.append(prepare_fastspeech_corpus(transcript_dict=build_path_to_transcript_dict_putin01(),
  File "/home/joe/tmp/IMS-Toucan/Utility/corpus_preparation.py", line 40, in prepare_fastspeech_corpus
    aligner_datapoints = AlignerDataset(transcript_dict, cache_dir=corpus_dir, lang=lang, phone_input=phone_input, device=torch.device("cuda"))
  File "/home/joe/tmp/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/AutoAligner/AlignerDataset.py", line 96, in __init__
    speaker_embedding_func_ecapa = EncoderClassifier.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb",
  File "/home/joe/tmp/env/lib/python3.10/site-packages/speechbrain/pretrained/interfaces.py", line 374, in from_hparams
    return cls(hparams["modules"], hparams, **kwargs)
  File "/home/joe/tmp/env/lib/python3.10/site-packages/speechbrain/pretrained/interfaces.py", line 786, in __init__
    super().__init__(*args, **kwargs)
  File "/home/joe/tmp/env/lib/python3.10/site-packages/speechbrain/pretrained/interfaces.py", line 187, in __init__
    module.to(self.device)
  File "/home/joe/tmp/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/home/joe/tmp/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/joe/tmp/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 688, in _apply
    self._buffers[key] = fn(buf)
  File "/home/joe/tmp/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/joe/tmp/env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

It's kind of strange, because in the same environment I have
>>> import torch
>>> torch.cuda.device_count()
1
>>> torch.cuda.is_available()
True
>>> torch.cuda.get_device_name()
'NVIDIA GeForce RTX 3060 Laptop GPU'

Could you tell me please, what is a possible problem here?

**Comment by Ca-ressemble-a-du-fake** [comment]
@Hardog4 did you try to reinstall nvidia drivers and Pytorch with cuda support ? Have a look at this it could help you https://stackoverflow.com/a/62361395/6351897

**Comment by Flux9665** [comment]
did you add the ```--gpu_id 0``` to your start command?

The GPU has to be set explicitly, even if it's the only one available. If no GPU is specified, all GPUs will be made invisible to prevent processes accidentially running on the wrong GPUs on multi-GPU servers.

**Comment by Hardog4** [comment]
> did you add the `--gpu_id 0` to your start command?
> 
> The GPU has to be set explicitly, even if it's the only one available. If no GPU is specified, all GPUs will be made invisible to prevent processes accidentially running on the wrong GPUs on multi-GPU servers.

It helped,  thank you!
