### ISSUE TITLE
downloader doesn't download NEB but read_text_to_file uses it

### ISSUE THREAD

**Issue by thoraxe** [DigitalPhonetics/IMS-Toucan#118]
* Clone the repo,
* install the requirements
* `run_model_downloader.py`
* `run_text_to_file_reader.py` 

Expected result:
`le_corbeau_et_le_renard` is generated.

Actual result:
```
Traceback (most recent call last):
  File "/home/thoraxe/voice-cloning/IMS-Toucan/run_text_to_file_reader.py", line 132, in <module>
    le_corbeau_et_le_renard(version="NEB_baseline", model_id="NEB", exec_device=exec_device)
  File "/home/thoraxe/voice-cloning/IMS-Toucan/run_text_to_file_reader.py", line 55, in le_corbeau_et_le_renard
    read_texts(model_id=model_id,
  File "/home/thoraxe/voice-cloning/IMS-Toucan/run_text_to_file_reader.py", line 9, in read_texts
    tts = PortaSpeechInterface(device=device, tts_model_path=model_id)
  File "/home/thoraxe/voice-cloning/IMS-Toucan/InferenceInterfaces/PortaSpeechInterface.py", line 68, in __init__
    checkpoint = torch.load(tts_model_path, map_location='cpu')
  File "/home/thoraxe/.pyenv/versions/toucan-310/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/thoraxe/.pyenv/versions/toucan-310/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/thoraxe/.pyenv/versions/toucan-310/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'Models/PortaSpeech_NEB/best.pt'
```

This is because the downloader does not download NEB.

**Comment by Ca-ressemble-a-du-fake** [comment]
Do you have a folder in Models names PortaSpeech_Meta ? If so replace NEB by `Meta` for model_id argument in 
https://github.com/DigitalPhonetics/IMS-Toucan/blob/e41e266ccacf282a9854d562f9e3d604f1cf245b/run_text_to_file_reader.py#L132

You can also change it in version which is used to create the output filename.

**Comment by Flux9665** [comment]
The NEB model should not be in this branch, that was an accident. It's part of a current experimental branch. The idea of this script is that you exchange the model ID for the model that you want to use. The code is just an example of what it might look like.

**Comment by Flux9665** [comment]
The script is now changed so that it should work by default.

**Comment by thoraxe** [comment]
LGTM, thanks for the fix!
