### ISSUE TITLE
Fine tuning on a personal created small dataset

### ISSUE THREAD

**Issue by AlexSteveChungAlvarez** [DigitalPhonetics/IMS-Toucan#129]
I am trying to fine tune with the previous and last versions of Toucan, but in both I get some errors. 
For the previous version, this is what appears:

```
(C:\Users\Aorus\Documents\Voice_Cloning_Quechua\toucan_conda_venv) C:\Users\Aorus\Documents\Voice_Cloning_Quechua>python run_training_pipeline.py fine_yf --gpu_id 0
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Preparing
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
... building dataset cache ...
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\Aorus\Documents\Voice_Cloning_Quechua\toucan_conda_venv\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Aorus\Documents\Voice_Cloning_Quechua\toucan_conda_venv\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Aorus\Documents\Voice_Cloning_Quechua\TrainingInterfaces\Text_to_Spectrogram\AutoAligner\AlignerDataset.py", line 123, in cache_builder_process
    _, sr = sf.read(path_list[0])
IndexError: list index out of range
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.60s/it] 
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.50s/it] 
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.51s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.75s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.87s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.20s/it]
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.89s/it] 
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.08s/it]

100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.04s/it] 
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.14s/it]
  File "C:\Users\Aorus\Documents\Voice_Cloning_Quechua\TrainingInterfaces\TrainingPipelines\FastSpeech2_finetuning_Yeshy.py", line 37, in run
    datasets.append(prepare_fastspeech_corpus(transcript_dict=build_path_to_transcript_dict_propio(),
  File "C:\Users\Aorus\Documents\Voice_Cloning_Quechua\Utility\corpus_preparation.py", line 38, in prepare_fastspeech_corpus
    train_aligner(train_dataset=aligner_datapoints,
  File "C:\Users\Aorus\Documents\Voice_Cloning_Quechua\TrainingInterfaces\Text_to_Spectrogram\AutoAligner\autoaligner_train_loop.py", line 129, in train_loop
    loss_this_epoch = sum(loss_sum) / len(loss_sum)
ZeroDivisionError: division by zero

```
While for the latest version, appears this:

```
(toucanvenv) C:\Users\Aorus\Documents\IMS-Toucan>python run_training_pipeline.py fine_yf --gpu_id 0
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Preparing
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
... building dataset cache ...
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Aorus\Documents\IMS-Toucan\TrainingInterfaces\Text_to_Spectrogram\AutoAligner\AlignerDataset.py", line 133, in cache_builder_process
    _, sr = sf.read(path_list[0])
IndexError: list index out of range
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.37s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.92s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.28s/it] 
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.96s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.39s/it]

100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.18s/it] 

100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.66s/it]

100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.90s/it]

100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.54s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.47s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.51s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.07s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.92s/it]

    destination.symlink_to(sourcepath)
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\pathlib.py", line 1403, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: [WinError 1314] El cliente no dispone de un privilegio requerido: 'C:\\Users\\Aorus\\.cache\\huggingface\\hub\\models--speechbrain--spkrec-ecapa-voxceleb\\snapshots\\5c0be3875fda05e81f3c004ed8c7c06be308de1e\\hyperparams.yaml' -> 'Models\\Embedding\\speechbrain_speaker_embedding_ecapa\\hyperparams.yaml'
```
I only have Windows to train on for the moment. If anyone can help, I appreciate it. I can share the created dataset if you require it. It is in the Spanish language.

**Comment by hakcats** [comment]
Just run your terminal (I am assuming you're using cmd) in admin mode.

**Comment by AlexSteveChungAlvarez** [comment]
OK, now for the latest version appears the same error as in the previous version, the ZeroDivisionError. But before that, there was another error, which I "solved" before in the previous version, the error was this:
```
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Preparing
Prepared an Aligner dataset with 19 datapoints in Corpora\dataset_propio\Yeshy.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Aorus\Documents\IMS-Toucan\run_training_pipeline.py", line 71, in <module>
    pipeline_dict[args.pipeline](gpu_id=args.gpu_id,
  File "C:\Users\Aorus\Documents\IMS-Toucan\TrainingInterfaces\TrainingPipelines\finetuning_example_personal.py", line 51, in run
    personal_set.append(prepare_fastspeech_corpus(transcript_dict=build_path_to_transcript_dict_propio(),
  File "C:\Users\Aorus\Documents\IMS-Toucan\Utility\corpus_preparation.py", line 42, in prepare_fastspeech_corpus
    train_aligner(train_dataset=aligner_datapoints,
  File "C:\Users\Aorus\Documents\IMS-Toucan\TrainingInterfaces\Text_to_Spectrogram\AutoAligner\autoaligner_train_loop.py", line 88, in train_loop
    for batch in tqdm(train_loader):
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\site-packages\torch\utils\data\dataloader.py", line 430, in __iter__
    self._iterator = self._get_iterator()
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ArticulatoryCombinedTextFrontend.__init__.<locals>.<lambda>'
```
And then appears this:
```
(toucanvenv) C:\Users\Aorus\Documents\IMS-Toucan>The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Aorus\anaconda3\envs\toucanvenv\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```
So, for this error in both versions, I changed the num_workers in the train_loader of the autoaligner_train_loop.py to 0. I think from there would come the ZeroDivisionError...But I have tried this with another dataset before and it worked, so I don't know why with this new dataset it doesn't.

**Comment by AlexSteveChungAlvarez** [comment]
@Flux9665 What do you suggest?

**Comment by Flux9665** [comment]
The first error `AttributeError: Can't pickle local object 'ArticulatoryCombinedTextFrontend.__init__.<locals>.<lambda>'
` sounds like there is a problem with the multiprocessing. Maybe it is about using fork or spawn as the ini method for subprocesses. I have never enountered this problem, so it's difficult to debug. I just modified the aligner train loop to manually set the file sharing strategy of the multiprocessing, maybe this fixes it, but I'm not sure. 

The ```EOFError``` happened for me in the past when I was trying to read a corrupted file. Maybe one of the audios in your dataset cannot be loaded correctly? Or maybe the cache file of the aligner dataset is corrupted? You could try deleting the cache file and re-extracting it. If it works for one dataset but not for the other, it has probably something to do with at least one of the audios in the dataset that doesn't work.

**Comment by AlexSteveChungAlvarez** [comment]
Yes, I had read that and tried it. I recorded myself the little dataset with python. You can take a look of the dataset here: https://drive.google.com/drive/folders/1kcyrP5U44PHZWgF58X9D5UQiAVIWUV5V?usp=share_link , maybe the way I recorded is not the correct one?

**Comment by Flux9665** [comment]
I see no problem with those audios, but I think I see the reason for the error now. Your dataset only has 18 samples, but the Aligner is trained with a batchsize of 32. So there are not enough samples to fill even a single batch. 

I'm going to add a safeguard to make sure that this doesn't just crash in the future, but I'd suggest anyway that you record a few more sentences until you have at least 40 or so. 

Also, because the quality is not the best, I recommend enhancing the audio quality with this: https://podcast.adobe.com/enhance 
I used it in the past to improve some problematic data and it worked wonders.

**Comment by AlexSteveChungAlvarez** [comment]
I tried with another dataset of about 300 samples and it returned the same `EOFError`. I changed the num_workers in the train_loader of the autoaligner_train_loop.py to 0, commented the prefetch factor and changed the persistent workers to False as I did before for training a 70 samples dataset with the previous version (the one that uses FastSpeech2) and it works now.
I didn't have time to record more samples for my own dataset, but I guess the `ZeroDivisionError` was because of not having enough samples to fill a batch as you say. Thank you for the audio enhance tool, I will be recording a new dataset in the next weeks and it will be very useful for this task. 
Is there a way to create a dataset for this purpose by recording the audios first, without having texts?

**Comment by Flux9665** [comment]
Regarding your question in the end: Sure, you can transcribe the audios later. Spontaneous speech and read speech are pretty different from one another, so reading a text or transcribing speech that was not read from a script lead to different types of data, whoch can then also lead to TTS with a very different speaking style. Most training data is read text, so that's what the pretrained models are trained on.

**Comment by AlexSteveChungAlvarez** [comment]
> I tried with another dataset of about 300 samples and it returned the same `EOFError`. I changed the num_workers in the train_loader of the autoaligner_train_loop.py to 0, commented the prefetch factor and changed the persistent workers to False as I did before for training a 70 samples dataset with the previous version (the one that uses FastSpeech2) and it works now.

I encountered the same EOFError for german datasets from common voice and multilingual librispeech, and a small dataset collected by me in spanish. With these steps the code works fine. For the english datasets of libritts and common voice the base code works fine.
