### ISSUE TITLE
RuntimeError + Indexerror when fine tuning on v25

### ISSUE THREAD

**Issue by thoraxe** [DigitalPhonetics/IMS-Toucan#135]
```
python run_training_pipeline.py --gpu_id 0 crewchief_jim
torchvision is not available - cannot save figures
Making GPU 0 the only visible device.
Preparing
... building dataset cache ...
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app-root/src/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/AutoAligner/AlignerDataset.py", line 132, in cache_builder_process
    _, sr = sf.read(path_list[0])
IndexError: list index out of range
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app-root/src/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/AutoAligner/AlignerDataset.py", line 132, in cache_builder_process
    _, sr = sf.read(path_list[0])
IndexError: list index out of range
Process Process-4:
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app-root/src/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/AutoAligner/AlignerDataset.py", line 132, in cache_builder_process
    _, sr = sf.read(path_list[0])
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app-root/src/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/AutoAligner/AlignerDataset.py", line 132, in cache_builder_process
    _, sr = sf.read(path_list[0])
IndexError: list index out of range
Converting into convenient format...
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/opt/app-root/src/IMS-Toucan/run_training_pipeline.py", line 104, in <module>
    pipeline_dict[args.pipeline](gpu_id=args.gpu_id,
  File "/opt/app-root/src/IMS-Toucan/TrainingInterfaces/TrainingPipelines/finetune_crewchief.py", line 40, in run
    english_datasets.append(prepare_fastspeech_corpus(transcript_dict=build_path_to_transcript_dict_generic_ljspeech("../CrewChiefV4/CrewChiefV4/sounds/"),
  File "/opt/app-root/src/IMS-Toucan/Utility/corpus_preparation.py", line 40, in prepare_fastspeech_corpus
    aligner_datapoints = AlignerDataset(transcript_dict, cache_dir=corpus_dir, lang=lang, phone_input=phone_input, device=torch.device("cuda"))
  File "/opt/app-root/src/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/AutoAligner/AlignerDataset.py", line 108, in __init__
    raise RuntimeError
RuntimeError
```

Not sure what to do here...

**Comment by thoraxe** [comment]
user error. I had the wrong path to the audio files.
