### ISSUE TITLE
AttributeError: 'Tag' object has no attribute 'value'

### ISSUE THREAD

**Issue by DiniMuhd7** [DigitalPhonetics/IMS-Toucan#150]
Converting into convenient format...
100% 6145/6145 [00:00<00:00, 42999.88it/s]
Traceback (most recent call last):
File "/content/IMS-Toucan/run_training_pipeline.py", line 106, in <module>
    pipeline_dict[args.pipeline](gpu_id=args.gpu_id,
File "/content/IMS-Toucan/TrainingInterfaces/TrainingPipelines/ToucanTTS_Swahili.py", line 28, in run
    train_set = prepare_fastspeech_corpus(transcript_dict=build_path_to_transcript_dict_swahili_integration(),
File "/content/IMS-Toucan/Utility/corpus_preparation.py", line 40, in prepare_fastspeech_corpus
    aligner_datapoints = AlignerDataset(transcript_dict, cache_dir=corpus_dir, lang=lang, phone_input=phone_input, device=torch.device("cuda"))
  File "/content/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/AutoAligner/AlignerDataset.py", line 95, in __init__
    speaker_embedding_func_ecapa = EncoderClassifier.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb",
  File "/usr/local/lib/python3.10/dist-packages/speechbrain/pretrained/interfaces.py", line 399, in from_hparams
    hparams = load_hyperpyyaml(fin, overrides)
  File "/usr/local/lib/python3.10/dist-packages/hyperpyyaml/core.py", line 157, in load_hyperpyyaml
    yaml_stream = resolve_references(yaml_stream, overrides, overrides_must_match)
  File "/usr/local/lib/python3.10/dist-packages/hyperpyyaml/core.py", line 325, in resolve_references
    _walk_tree_and_resolve("root", preview, preview, file_path)
  File "/usr/local/lib/python3.10/dist-packages/hyperpyyaml/core.py", line 372, in _walk_tree_and_resolve
    current_node[k] = _walk_tree_and_resolve(sub_key, sub_node, tree, file_path)
  File "/usr/local/lib/python3.10/dist-packages/hyperpyyaml/core.py", line 372, in _walk_tree_and_resolve
    current_node[k] = _walk_tree_and_resolve(sub_key, sub_node, tree, file_path)
  File "/usr/local/lib/python3.10/dist-packages/hyperpyyaml/core.py", line 376, in _walk_tree_and_resolve
    tag_value = current_node.tag.value or ""
AttributeError: 'Tag' object has no attribute 'value'

**Comment by DiniMuhd7** [comment]
Refer to (https://github.com/m-bain/whisperX/issues/295)

**Comment by Flux9665** [comment]
Cannot reproduce, but from your error message I see it has something to do with the speechbrain dependency, not the toucan toolkit itself. So I can't help with this, sorry.
