### ISSUE TITLE
Error when running weight averaging.

### ISSUE THREAD

**Issue by michael-conrad** [DigitalPhonetics/IMS-Toucan#24]
```python
python run_weight_averaging.py 
selecting checkpoints...
selecting checkpoints...
loading model Models/FastSpeech2_Cherokee_West/checkpoint_200000.pt
loading model Models/FastSpeech2_Cherokee_West/checkpoint_199000.pt
loading model Models/FastSpeech2_Cherokee_West/checkpoint_198000.pt
loading model Models/FastSpeech2_Cherokee_West/checkpoint_197000.pt
loading model Models/FastSpeech2_Cherokee_West/checkpoint_196000.pt
averaging...
saving model...
...done!
selecting checkpoints...
Traceback (most recent call last):
  File "run_weight_averaging.py", line 120, in <module>
    make_best_in_all(n=5)
  File "run_weight_averaging.py", line 105, in make_best_in_all
    averaged_model, default_embed = average_checkpoints(checkpoint_paths, load_func=load_net_fast)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by Flux9665** [comment]
It looks like you have a directory in your Models directory that's empty, so the script looks for models to average in there, but doesn't find any. I'm going to hotfix it later.

**Comment by Flux9665** [comment]
Actually, such a check was already in place. I tried to make it capture some more, but I don't think there's much of a difference. I don't see a reason why this would fail, you probably have a file somewhere in the Models directory or in one of its subdirectories which the function parsing for checkpoints doesn't expect.

**Comment by michael-conrad** [comment]
Thanks. Yes, that is very likely...
