### ISSUE TITLE
RuntimeError: Pin memory thread exited unexpectedly while fine tuning with 100 samples in dataset

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#96]
Hi,

I wanted to fine tune the Meta model on my 100 sample dataset until 60 k steps but it failed with memory issue after 9k steps. The error trace is the following : 
`
Steps:              9912
  0%|                                                                   | 0/2 [00:00<?, ?it/s]Exception in thread Thread-5 (_pin_memory_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/caraduf/ToucanTTS/toucanenv/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 49, in _pin_memory_loop
    do_one_step()
  File "/home/caraduf/ToucanTTS/toucanenv/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 26, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/caraduf/ToucanTTS/toucanenv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 322, in rebuild_storage_filename
    storage = torch.UntypedStorage._new_shared_filename_cpu(manager, handle, size)
RuntimeError: unable to mmap 25664 bytes from file </torch_3135439_4056562685_15644>: Cannot allocate memory (12)
  0%|                                                                   | 0/2 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/caraduf/ToucanTTS/IMS-Toucan/run_training_pipeline.py", line 71, in <module>
    pipeline_dict[args.pipeline](gpu_id=args.gpu_id,
  File "/home/caraduf/ToucanTTS/IMS-Toucan/TrainingInterfaces/TrainingPipelines/finetuning_LS.py", line 87, in run
    train_loop(net=model,
  File "/home/caraduf/ToucanTTS/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/PortaSpeech/portaspeech_train_loop_arbiter.py", line 53, in train_loop
    mono_language_loop(net=net,
  File "/home/caraduf/ToucanTTS/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/PortaSpeech/portaspeech_train_loop.py", line 115, in train_loop
    for batch in tqdm(train_loader):
  File "/home/caraduf/ToucanTTS/toucanenv/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/caraduf/ToucanTTS/toucanenv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/caraduf/ToucanTTS/toucanenv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/home/caraduf/ToucanTTS/toucanenv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1277, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly
`
I don't know which memory is concerned by `RuntimeError: unable to mmap 25664 bytes from file ` whether it is RAM, VRAM, or swap.

However according to WandB VRAM was used at about 33%, System RAM was 75% before the training aborted. So swap may be the cause (even though it is not reported in WandB) ?

What do you think should I increase swap (it is actually 2GB) although [someone with the same error did it without success](https://stackoverflow.com/a/67969244) ?

Any help appreciated,

**Comment by Ca-ressemble-a-du-fake** [comment]
Even after increasing the swap to 16GB the same error appears and the training stops after 110 minutes (after roughly 4k new steps ).

I am now trying again with 4 workers in the Dataloader for the training loop. I'll keep you posted.

Edit : I tested with 4 workers and now the training halted after 110 minutes again (roughly 4k new steps). In WandB nothing looks weird losses keep decreasing, GPU temperature is below 40°C. 

The only weird thing is "disk utilization %" which reaches 97,7 at the time the training hangs (and then remains constant at this value). Although disk is an SSD with still more than 40GB of free space.

For completeness `htop` shows 11.1G / 15.5G for the memory and 345M/16.0G for the swap, and `nvidia-smi` reports 8GB / 24GB with 0% GPU util.

**Comment by Flux9665** [comment]
Hmm, I cannot really think of any reason something would utilize the disk so much other than writing a checkpoint. So it is  weird that this issue occured so late in training. Does the issue still persist, or did you find a solution in the meantime? The pin memory is a special region of the memory, maybe this has a hard limit and turning pin_memory off in the dataloader could fix this.

**Comment by Ca-ressemble-a-du-fake** [comment]
I can't remember how I solved it. Maybe decreasing the number of workers and some other things that were hard coded. For sure it was solved and did never reappear. Thanks anyway for your follow up.
